name: Flutter_Tests

on:
  push:
    branches: [testes]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2.4.0
        with:
          flutter-version: '3.0.2'
          channel: 'stable'
        - run: flutter --version